# Database
spring.datasource.url=jdbc:mysql://localhost:3306/university_events
spring.datasource.username=root
spring.datasource.password=SLNSswetha@360

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Server
server.port=8082

# Thymeleaf
spring.thymeleaf.cache=false

